//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prism.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prism.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE APPLICATION ENCOUNTERED AN UNHANDLED EXCEPTION - {0}.
        /// </summary>
        internal static string ApplicationEncounterUnhandledException {
            get {
                return ResourceManager.GetString("ApplicationEncounterUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has not been fully initialized.  Use a platform initializer to complete initialization..
        /// </summary>
        internal static string ApplicationIsNotInitialized {
            get {
                return ResourceManager.GetString("ApplicationIsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A: {0}, R: {1}, G: {2}, B: {3}.
        /// </summary>
        internal static string ARGB {
            get {
                return ResourceManager.GetString("ARGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to set the value of a read-only property..
        /// </summary>
        internal static string AttemptedToSetReadOnlyProperty {
            get {
                return ResourceManager.GetString("AttemptedToSetReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot combine zero paths..
        /// </summary>
        internal static string CannotCombineZeroPaths {
            get {
                return ResourceManager.GetString("CannotCombineZeroPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate an event with the name &apos;{0}&apos; and the handler type &apos;{1}&apos; for the type {2}..
        /// </summary>
        internal static string CannotLocateEventWithNameAndHandlerForType {
            get {
                return ResourceManager.GetString("CannotLocateEventWithNameAndHandlerForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate an event with the name &apos;{0}&apos; for the type {1}..
        /// </summary>
        internal static string CannotLocateEventWithNameForType {
            get {
                return ResourceManager.GetString("CannotLocateEventWithNameForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate a property with the name &apos;{0}&apos; and the type &apos;{1}&apos; for the type {2}..
        /// </summary>
        internal static string CannotLocatePropertyWithNameAndTypeForType {
            get {
                return ResourceManager.GetString("CannotLocatePropertyWithNameAndTypeForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate a type loader for the type &apos;{0}&apos; and name &apos;{1}&apos;..
        /// </summary>
        internal static string CannotLocateTypeLoaderForType {
            get {
                return ResourceManager.GetString("CannotLocateTypeLoaderForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot override metadata on a read-only property..
        /// </summary>
        internal static string CannotOverrideMetadataOnReadOnlyProperty {
            get {
                return ResourceManager.GetString("CannotOverrideMetadataOnReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot push a view that is already on the stack..
        /// </summary>
        internal static string CannotPushExistingView {
            get {
                return ResourceManager.GetString("CannotPushExistingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve indexer for property path token &apos;{0}&apos;..
        /// </summary>
        internal static string CannotResolveIndexerForPathToken {
            get {
                return ResourceManager.GetString("CannotResolveIndexerForPathToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve property path &apos;{0}&apos; for provided object..
        /// </summary>
        internal static string CannotResolvePropertyPathForObject {
            get {
                return ResourceManager.GetString("CannotResolvePropertyPathForObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller does not implement {0}..
        /// </summary>
        internal static string ControllerDoesNotImplementInterface {
            get {
                return ResourceManager.GetString("ControllerDoesNotImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller successfully loaded and returned &apos;{0}&apos;..
        /// </summary>
        internal static string ControllerLoadedAndReturnedPerspective {
            get {
                return ResourceManager.GetString("ControllerLoadedAndReturnedPerspective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller load failed with message &apos;{0}&apos;..
        /// </summary>
        internal static string ControllerLoadFailedWithMessage {
            get {
                return ResourceManager.GetString("ControllerLoadFailedWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller&apos;s ModelType cannot be null..
        /// </summary>
        internal static string ControllerModelTypeCannotBeNull {
            get {
                return ResourceManager.GetString("ControllerModelTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An EventDescriptor for the event &apos;{0}&apos; and owning type &apos;{1}&apos; has already been created.  Only one EventDescriptor is allowed per event..
        /// </summary>
        internal static string EventDescriptorAlreadyCreated {
            get {
                return ResourceManager.GetString("EventDescriptorAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set value &apos;{0}&apos; on target property &apos;{1}&apos;.  {2}.
        /// </summary>
        internal static string FailedToSetValueOnTargetProperty {
            get {
                return ResourceManager.GetString("FailedToSetValueOnTargetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} controller classes with navigation attributes..
        /// </summary>
        internal static string FoundControllersWithNavAttributesPlural {
            get {
                return ResourceManager.GetString("FoundControllersWithNavAttributesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} controller class with navigation attributes..
        /// </summary>
        internal static string FoundControllersWithNavAttributesSingular {
            get {
                return ResourceManager.GetString("FoundControllersWithNavAttributesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} view classes with proper view perspectives..
        /// </summary>
        internal static string FoundViewsWithPerspectivesPlural {
            get {
                return ResourceManager.GetString("FoundViewsWithPerspectivesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} view class with proper view perspectives..
        /// </summary>
        internal static string FoundViewsWithPerspectivesSingular {
            get {
                return ResourceManager.GetString("FoundViewsWithPerspectivesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaN or infinity height returned from arrangement..
        /// </summary>
        internal static string InvalidHeightReturnedFromArrangement {
            get {
                return ResourceManager.GetString("InvalidHeightReturnedFromArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaN or infinity height returned from measurement..
        /// </summary>
        internal static string InvalidHeightReturnedFromMeasurement {
            get {
                return ResourceManager.GetString("InvalidHeightReturnedFromMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaN or infinity width returned from arrangement..
        /// </summary>
        internal static string InvalidWidthReturnedFromArrangement {
            get {
                return ResourceManager.GetString("InvalidWidthReturnedFromArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaN or infinity width returned from measurement..
        /// </summary>
        internal static string InvalidWidthReturnedFromMeasurement {
            get {
                return ResourceManager.GetString("InvalidWidthReturnedFromMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left: {0}, Top: {1}, Right: {2}, Bottom: {3}.
        /// </summary>
        internal static string LeftTopRightBottom {
            get {
                return ResourceManager.GetString("LeftTopRightBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading controller of type {0}..
        /// </summary>
        internal static string LoadingControllerOfType {
            get {
                return ResourceManager.GetString("LoadingControllerOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched URI {0} with pattern {1}..
        /// </summary>
        internal static string MatchedURIWithPattern {
            get {
                return ResourceManager.GetString("MatchedURIWithPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata type must be the same as, or derive from, base metadata type of {0}..
        /// </summary>
        internal static string MetadataMustBeSameAsOrDeriveFromBase {
            get {
                return ResourceManager.GetString("MetadataMustBeSameAsOrDeriveFromBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}, Value: {1}.
        /// </summary>
        internal static string NameValue {
            get {
                return ResourceManager.GetString("NameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The native application could not be resolved..
        /// </summary>
        internal static string NativeApplicationCouldNotBeResolved {
            get {
                return ResourceManager.GetString("NativeApplicationCouldNotBeResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to controller type {0}..
        /// </summary>
        internal static string NavigatingToControllerType {
            get {
                return ResourceManager.GetString("NavigatingToControllerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to {0}..
        /// </summary>
        internal static string NavigatingToURI {
            get {
                return ResourceManager.GetString("NavigatingToURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No controller was found for URI {0}..
        /// </summary>
        internal static string NoControllerFoundForURI {
            get {
                return ResourceManager.GetString("NoControllerFoundForURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null reuse identifier returned..
        /// </summary>
        internal static string NullReuseIdReturned {
            get {
                return ResourceManager.GetString("NullReuseIdReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null view perspective given.  Cannot output a view.  If this was intentional, then this message can be ignored..
        /// </summary>
        internal static string NullViewPerspectiveReturned {
            get {
                return ResourceManager.GetString("NullViewPerspectiveReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not a descendant of this instance..
        /// </summary>
        internal static string ObjectIsNotADescendant {
            get {
                return ResourceManager.GetString("ObjectIsNotADescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not an ancestor of this instance..
        /// </summary>
        internal static string ObjectIsNotAnAncestor {
            get {
                return ResourceManager.GetString("ObjectIsNotAnAncestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one color must be specified..
        /// </summary>
        internal static string OneColorMinimum {
            get {
                return ResourceManager.GetString("OneColorMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner type does not match type of current instance..
        /// </summary>
        internal static string OwnerTypeDoesNotMatchCurrentType {
            get {
                return ResourceManager.GetString("OwnerTypeDoesNotMatchCurrentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform successfully initialized.  Running {0} v{1}..
        /// </summary>
        internal static string PlatformInitialized {
            get {
                return ResourceManager.GetString("PlatformInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A popup cannot present itself..
        /// </summary>
        internal static string PopupCannotPresentSelf {
            get {
                return ResourceManager.GetString("PopupCannotPresentSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified object is already presenting a popup.  Only one popup may be presented by an object at a time..
        /// </summary>
        internal static string PresenterAlreadyPresentingPopup {
            get {
                return ResourceManager.GetString("PresenterAlreadyPresentingPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PropertyDescriptor for the property {0} and owning type {1} has already been created.  Only one PropertyDescriptor is allowed per property..
        /// </summary>
        internal static string PropertyDescriptorAlreadyCreated {
            get {
                return ResourceManager.GetString("PropertyDescriptorAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is read-only..
        /// </summary>
        internal static string PropertyIsReadOnly {
            get {
                return ResourceManager.GetString("PropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property metadata has been sealed and cannot be modified..
        /// </summary>
        internal static string PropertyMetadataHasBeenSealed {
            get {
                return ResourceManager.GetString("PropertyMetadataHasBeenSealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property path contains an argument that exceeds the upper or lower bounds of the path parameters..
        /// </summary>
        internal static string PropertyPathArgumentExceedsBounds {
            get {
                return ResourceManager.GetString("PropertyPathArgumentExceedsBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property path contains a closing bracket without a corresponding opening bracket..
        /// </summary>
        internal static string PropertyPathContainsUnmatchedClosingBracket {
            get {
                return ResourceManager.GetString("PropertyPathContainsUnmatchedClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property path contains an opening bracket without a corresponding closing bracket..
        /// </summary>
        internal static string PropertyPathContainsUnmatchedOpeningBracket {
            get {
                return ResourceManager.GetString("PropertyPathContainsUnmatchedOpeningBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to output view of type {0}..
        /// </summary>
        internal static string ReadyToOutputViewOfType {
            get {
                return ResourceManager.GetString("ReadyToOutputViewOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle contains a NaN or infinite value..
        /// </summary>
        internal static string RectangleContainsNaNOrInfiniteValue {
            get {
                return ResourceManager.GetString("RectangleContainsNaNOrInfiniteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle size contains a negative value..
        /// </summary>
        internal static string RectangleSizeContainsNegativeValue {
            get {
                return ResourceManager.GetString("RectangleSizeContainsNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered {0} types to IoC container..
        /// </summary>
        internal static string RegisteredTypesToIoCContainerPlural {
            get {
                return ResourceManager.GetString("RegisteredTypesToIoCContainerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered {0} type to IoC container..
        /// </summary>
        internal static string RegisteredTypesToIoCContainerSingular {
            get {
                return ResourceManager.GetString("RegisteredTypesToIoCContainerSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A registered INativeWindow type with the name &apos;{0}&apos; is required..
        /// </summary>
        internal static string RegisteredWindowWithNameRequired {
            get {
                return ResourceManager.GetString("RegisteredWindowWithNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size contains a NaN or infinite value..
        /// </summary>
        internal static string SizeContainsNaNOrInfiniteValue {
            get {
                return ResourceManager.GetString("SizeContainsNaNOrInfiniteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size contains a negative value..
        /// </summary>
        internal static string SizeContainsNegativeValue {
            get {
                return ResourceManager.GetString("SizeContainsNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified string resource could not be found..
        /// </summary>
        internal static string StringResourceCouldNotBeFound {
            get {
                return ResourceManager.GetString("StringResourceCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; could not be resolved..
        /// </summary>
        internal static string TypeCouldNotBeResolved {
            get {
                return ResourceManager.GetString("TypeCouldNotBeResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type already has metadata specified..
        /// </summary>
        internal static string TypeHasMetadata {
            get {
                return ResourceManager.GetString("TypeHasMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must resolve to an object of type &apos;{1}&apos;..
        /// </summary>
        internal static string TypeMustResolveToType {
            get {
                return ResourceManager.GetString("TypeMustResolveToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate a view stack for the view..
        /// </summary>
        internal static string UnableToLocateViewStack {
            get {
                return ResourceManager.GetString("UnableToLocateViewStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate a view with perspective &apos;{0}&apos; and model type {1}.  Canceling output..
        /// </summary>
        internal static string UnableToLocateViewWithPerspectiveAndModelType {
            get {
                return ResourceManager.GetString("UnableToLocateViewWithPerspectiveAndModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be infinity..
        /// </summary>
        internal static string ValueCannotBeInfinity {
            get {
                return ResourceManager.GetString("ValueCannotBeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be less than 1..
        /// </summary>
        internal static string ValueCannotBeLessThanOne {
            get {
                return ResourceManager.GetString("ValueCannotBeLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be less than zero..
        /// </summary>
        internal static string ValueCannotBeLessThanZero {
            get {
                return ResourceManager.GetString("ValueCannotBeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be NaN or infinity..
        /// </summary>
        internal static string ValueCannotBeNaNOrInfinity {
            get {
                return ResourceManager.GetString("ValueCannotBeNaNOrInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be NaN or negative infinity..
        /// </summary>
        internal static string ValueCannotBeNaNOrNegativeInfinity {
            get {
                return ResourceManager.GetString("ValueCannotBeNaNOrNegativeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null, empty, or whitespace-only..
        /// </summary>
        internal static string ValueCannotBeNullEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("ValueCannotBeNullEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View is not a part of the stack..
        /// </summary>
        internal static string ViewIsNotPartOfStack {
            get {
                return ResourceManager.GetString("ViewIsNotPartOfStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width: {0}, Height: {1}.
        /// </summary>
        internal static string WidthHeight {
            get {
                return ResourceManager.GetString("WidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0}, Y: {1}.
        /// </summary>
        internal static string XY {
            get {
                return ResourceManager.GetString("XY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0}, Y: {1}, Width: {2}, Height: {3}.
        /// </summary>
        internal static string XYWidthHeight {
            get {
                return ResourceManager.GetString("XYWidthHeight", resourceCulture);
            }
        }
    }
}
